name: "Mi primer workflow"

on:
  workflow_dispatch:
  
  push:
     branches: 
      - main
      - feature/*
      
      
jobs:
  compile: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with: 
          node-version: 18.x
          
      - name: Install and build
        run: npm ci -- silent
          - name: Install
        run: npm ci --silent

      - name: Build
        run: npm run build -ws --if-present

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
    
        

 
        
         
  
